PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX sherlock: <http://data-iremus.huma-num.fr/ns/sherlockmei#>

SELECT ?annotation ?annotationName
WHERE {
    GRAPH <http://data-iremus.huma-num.fr/graph/modality-tonality> {
        ?analysis crm:P16_used_specific_object <http://data-iremus.huma-num.fr/id/eff6f0a7-cf80-402c-953b-c66161051356> .
        ?analysis crm:P9_consists_of ?annotation .
        ?annotation crm:P177_assigned_property_of_type ?annotationName .
        FILTER (regex(str(?annotationName),"http://modality-tonality.huma-num.fr/Zarlino_1558#")) .
    }
}