PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX dcterm: <http://purl.org/dc/terms/>
PREFIX sherlock: <http://data-iremus.huma-num.fr/ns/sherlockmei#>
SELECT ?annotation ?concept
WHERE {
    GRAPH <http://data-iremus.huma-num.fr/graph/modality-tonality> {
        ?e13 crm:P141_assigned <http://data-iremus.huma-num.fr/id/eff6f0a7-cf80-402c-953b-c66161051356_d1e16906>.
        ?e13 crm:P177_assigned_property_of_type ?concept.
        ?e13 crm:P140_assigned_attribute_to ?entity.
        ?annotation crm:P141_assigned ?entity 
    }
}
