PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX dcterm: <http://purl.org/dc/terms/>
PREFIX sherlockmei: <http://data-iremus.huma-num.fr/ns/sherlockmei#>
SELECT ?selection ?entities ?contributor
FROM <http://data-iremus.huma-num.fr/graph/modality-tonality>
FROM <http://data-iremus.huma-num.fr/graph/sherlock>
WHERE {
    ?selection dcterm:creator ?contributor
    {
        SELECT ?selection ((COUNT(?entity)) AS ?entities)
        WHERE {
            ?entity sherlockmei:in_score <http://data-iremus.huma-num.fr/id/31bbbea9-98a9-4c3a-9276-734ba9e949e2>.
            ?selection crm:P106_is_composed_of ?entity.
            ?selection crm:P2_has_type <http://data-iremus.huma-num.fr/id/9d0388cb-a178-46b2-b047-b5a98f7bdf0b>.
        }
        GROUP BY ?selection
    }
}
