PREFIX sherlock: <http://data-iremus.huma-num.fr/ns/sherlockmei#>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT ?annotation ?date ?contributor
FROM <http://data-iremus.huma-num.fr/graph/sherlock>
FROM <http://data-iremus.huma-num.fr/graph/modality-tonality>
WHERE {
    ?annotation crm:P140_assigned_attribute_to <http://data-iremus.huma-num.fr/id/eff6f0a7-cf80-402c-953b-c66161051356-beat-3-1.0>.
    ?annotation dcterms:created ?date.
    ?annotation crm:P14_carried_out_by ?contributor.
}
