nodeLinker: node-modules

packageExtensions:
  "@testing-library/user-event@*":
    peerDependenciesMeta:
      "@testing-library/dom":
        optional: true
  eslint-plugin-flowtype@*:
    peerDependenciesMeta:
      "@babel/plugin-syntax-flow":
        optional: true
      "@babel/plugin-transform-react-jsx":
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-4.1.0.cjs
