// MODES
export const INSPECTION = 'INSPECTION'
export const SELECTION = 'SELECTION'

// LISTS
export const CONCEPTS = 'INSPECTION'
export const SELECTIONS = 'SELECTION'
export const ANNOTATIONS = 'ANNOTAIONS'