name: Deploy prod
on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
      
       - name: Rename
        run: mv dist tonalities

       - name: Deploy
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "tonalities"
          target: sherlock/apache/public_html/